repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: .venv/bin/pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc",
            "--load-plugins=pylint.extensions.docparams",
          ]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.4                          # alinhe com a versão do uv que você usa
    hooks:
      # 1. Garante que o uv.lock esteja sempre atualizado
      - id: uv-lock

      # 2. Exporta todas as dependências para requirements.txt
      - id: uv-export
        name: Export all dependencies
        args:
          # --frozen garante que falhe se o lockfile não estiver sincronizado
          - --frozen
          # saída para requirements.txt
          - --output-file=requirements.txt