repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: .venv/bin/pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc",
            "--load-plugins=pylint.extensions.docparams",
          ]

  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'source .venv/bin/activate && pip freeze > requirements.txt && git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [pre-commit]